name: Publish Docker Image on Merge to Master
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Get NPM Version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
    - name: Publish to Docker Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: akkeris/cli
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ steps.package-version.outputs.current-version}}"